### PR TITLE
TSALC - TS Rev. A, GLV Rev. A.

### PR DESCRIPTION
**Pull request by michaelpass**
GLV:
Screen Shot 2019-04-10 at 3 08 03 PM

TS:

Screen Shot 2019-04-10 at 3 08 35 PM

Two boards have been created to aide in GLV/TS separation.
This two board design also cuts down on cost. The Powerex is the biggest unknown here.

Outstanding issues:
The input electrolytic EDA files haven't come in yet. These should arrive within a day. In the meantime, I've used the same electrolytic (the output cap) all around. *This must be changed in the schematic and PCB when the EDA files arrive.* Datasheet was difficult to read, as it was for the entire capacitor series, with the series having two possible lead pitches. Coding was too difficult to determine the version selected. The part number has been captured and will be processed in the BOM accordingly.

Changes to consider in the future:
- Better Powerex placement (can legs be bent)
- Fusing of powerex
- 15V compatibility with LED.

Note: 15V should be compatible with 12V LEDs. The main difference this would impose is the choice of current limiting resistors. These are for the TSALC. I'm guessing that for the aluminum body resistors (SuperLED purchased), that the 25% current increase from 12V to 15V shouldn't matter. Note, the TSAL LEDS worked without a resistor, so we should be fine here.

### CODE REVIEW

**Comment by michaelpass** [comment]
Note: Change HV+_POST_AIR+ to MOT_CUR+. More explanative. Ambiguity as to whether this refers to the battery terminal net, or the actual vehicle run.

**Comment by michaelpass** [comment]
Note: Is there a more appropriate MOSFET for Q1 (NE555timer)?

**Comment by michaelpass** [comment]
Note: Double check 555 timer.

**Comment by michaelpass** [comment]
Note: Add timer calculations.

**Comment by anshuman2601** [comment]
55909771-735fd280-5ba2-11e9-90ad-093426bfd990_LI

Is the highlighted part extra? What is it's use? 
Can you provide more explanation as to what SH1 & SH2 are.

**Review by anshuman2601 — CHANGES_REQUESTED** [review]
Comment posted. But overall approved, minus the extra wiring at the bottom. Would be helpful to have it's use listed.

**Comment by michaelpass** [comment]
> Is the highlighted part extra? What is it's use?

This is not extra. This is used to bridge the ground pours on either side. When we route traces through the board, we potentially carve out little islands of ground pour. These islands have to be reconnected. The easiest way is to put two vias on either side of the divide, and then run a via across.

This is the situation:
Screen Shot 2019-04-11 at 2 04 13 PM

The signals get carved out, producing islands. We have to reconnect the islands.

> Can you provide more explanation as to what SH1 & SH2 are.
 
These are shorts. They’re a hack in eagle to allow us to connect two nets directly. EAGLE only allows 1 name per net. As as soon as I connect wires together, they become the same net. This is just how EAGLE works.

But it doesn't allow me to easily connect a net called "DISCHARGE_COIL+" directly to a net called "+12V-ISO". My connector would just have both have one name. This is confusing in reading the PCB layout. Technically, EAGLE is correct, and I can always get aways with using one net name. But it's difficult to visualize.  

So I create a hack. I create a device called "SH$" (short) 

Screen Shot 2019-04-11 at 2 08 29 PM

This gives me two points that are connected in the PCB as one wire, but what EAGLE considers two pads.

Screen Shot 2019-04-11 at 2 08 59 PM

This will create an overlap DRC rule for the part, but I can easily approve this and move on with my life. The schematic is easier to read, and it has little imposition on my life, apart from the confusion it might create for someone sourcing a BOM.

This part can be ignored. But overall, it creates a more readable schematic/PCB.

**Comment by michaelpass** [comment]
> Comment posted. But overall approved, minus the extra wiring at the bottom. Would be helpful to have it's use listed.

What changes exactly did you wish to see?
You need to state when you request changes, I would like to see:
- Item 1
- Item 2
- Item 3

**Pull request merged**
