### PR TITLE
TSMP Board Major Revision Update

### PR DESCRIPTION
**Pull request by anshuman2601**
Completed board, minus the connector. Still needs verification from @michaelpass .
1. Needs update on the dimensions preferably.
2. Mount holes required.
3. Perform resistor package check, with regards to the board size.

### CODE REVIEW

**Comment by michaelpass** [comment]
👎 (Merge not yet approved)
-----------------------------
The board is on the right track, but has a few things that need to be changed about it.
I've made some changes and have pushed them up to origin/anshu-TSMPC.
You'll want to check this out: 
`git fetch --all`
`git checkout anshu-TSMPC`
`git merge origin/anshu-TSMPC`

The majority of remaining work will be in selecting appropriate HV connectors. This has to be done for FUSE, though.

**Pros:**
- Overall layout concept is correct (major revisions needed on connector, see more below).
- Board size is very good. (3.299 in x 2.137 in is under the 3.933 x 3.933 limitation) 

**Cons:**

- Board is Tractive System Measuring Point Circuit (TSMPC), not temperature sensing.
- Proper isolation has not been done for GLV/TS parts.
- Connector **must** be changed. (Since this is a HV system, we'll likely want to go with whatever connector series we have picked out for our FUSE board to reduce compliance/documentation burden. The number of connections here is much smaller than the 23 or so on the FUSE connectors, so we'll want to go with smaller connectors that match with:

1. 1 or 2-pos connector for HV+ (2-pos is usually the minimum. If so, we can short these ends to give some connector redundancy)
2. 1 or 2-pos connector for HV-
3. 2-pos connector for HV+ and HV- measuring points (these can be close to each other because they are seperated with, at minimum, 10k in parallel = 5k)[Note: These connections are what go to the TSMP banana plugs)
4. 4-pos Chassis ground input connector (multiple sample points to chassis ground)
5. 2-pos Chassis ground output connector  (this goes 

The reason for this is that we want to maintain proper isolation between HV+ and HV-. We don't want to bring them close to each other, because you can get arcing. And we don't want to bring our TS stuff close to our GLV stuff.  

@rgoedken: We could move our chassis measuring point onto a different board for even better isolation. I'd like your input on this.

@anshuman2601 - Other changes that were made, that should be incorporated on future boards:
- Board mounting  holes must be placed.

- Part renumbering (parts must be logically numbered on board. Because things were deleted/added, part numbers don't start logically on the schematic.)

- Board trace widths can be changed. Here, we want really good connections, so I made the width around 30. Higher power traces also need bigger widths, but here, we are doing this for improved connection.

- Font size done as vectored, and made smaller.

- Resistors were turned around so that ends met. If you are stepping up resistors in a ladder like this, you want to put the ends closest to each other to minimize routing time. This makes it easier to refactor.

**Review by michaelpass — CHANGES_REQUESTED** [review]
👎 (Merge not yet approved)
-----------------------------
The board is on the right track, but has a few things that need to be changed about it.
I've made some changes and have pushed them up to origin/anshu-TSMPC.

My work:
Screen Shot 2019-04-06 at 4 44 18 AM


You'll want to check this out: 
`git fetch --all`
`git checkout anshu-TSMPC`
`git merge origin/anshu-TSMPC`

The majority of remaining work will be in selecting appropriate HV connectors. This has to be done for FUSE, though.

**Pros:**
- Overall layout concept is correct (major revisions needed on connector, see more below).
- Board size is very good. (3.299 in x 2.137 in is under the 3.933 x 3.933 limitation) 

**Cons:**

- Board is Tractive System Measuring Point Circuit (TSMPC), not temperature sensing.
- Proper isolation has not been done for GLV/TS parts.
- Connector **must** be changed. (Since this is a HV system, we'll likely want to go with whatever connector series we have picked out for our FUSE board to reduce compliance/documentation burden. The number of connections here is much smaller than the 23 or so on the FUSE connectors, so we'll want to go with smaller connectors that match with:

1. 1 or 2-pos connector for HV+ (2-pos is usually the minimum. If so, we can short these ends to give some connector redundancy)
2. 1 or 2-pos connector for HV-
3. 2-pos connector for HV+ and HV- measuring points (these can be close to each other because they are seperated with, at minimum, 10k in parallel = 5k)[Note: These connections are what go to the TSMP banana plugs)
4. 4-pos Chassis ground input connector (multiple sample points to chassis ground)
5. 2-pos Chassis ground output connector  (this goes 

The reason for this is that we want to maintain proper isolation between HV+ and HV-. We don't want to bring them close to each other, because you can get arcing. And we don't want to bring our TS stuff close to our GLV stuff.  

@rgoedken: We could move our chassis measuring point onto a different board for even better isolation. I'd like your input on this.

@anshuman2601 - Other changes that were made, that should be incorporated on future boards:
- Board mounting  holes must be placed.
Example:
Screen_Shot_2019-04-06_at_3_16_21_AM


- Part renumbering (parts must be logically numbered on board. Because things were deleted/added, part numbers don't start logically on the schematic.)
Example:
Screen Shot 2019-04-06 at 4 32 46 AM


- Board trace widths can be changed. Here, we want really good connections, so I made the width around 30. Higher power traces also need bigger widths, but here, we are doing this for improved connection.
Example:
Screen Shot 2019-04-06 at 4 30 59 AM


- Font size done as vectored, and made smaller.
Example:
Screen Shot 2019-04-06 at 3 56 51 AM


- Resistors were turned around so that ends met. If you are stepping up resistors in a ladder like this, you want to put the ends closest to each other to minimize routing time. This makes it easier to refactor.
Example:
Screen Shot 2019-04-06 at 3 07 22 AM (2)



Note: This is similar to our current connector:
en3646-product

This will be too expensive to use, and was just something I was playing around with. 
I think that we found something worthwhile in the Slack (I believe the TE AMP-DUAC series). We'll want to look into that. Again, once you select a connector for FUSE, we'll likely just want to use that for all of our TS connections.

**Comment by michaelpass** [comment]
Also, worth mentioning here that I removed the ground pour for multiple reasons. 
* A ground pour is used for multiple connections to ground
* We don't have multiple connections to ground
* The ground pour would create areas of close copper between the TS lines and the GLV of the chassis ground that would be connected to the ground pour

Lastly, the biggest additional piece of work that I've added from this pull request (above and beyond the revisions to this board) is the addition of another simple PCB to handle the chassis GND connection.

Again, this will be a simple board that will have two connectors. I'll create it in master after this gets merged in.
The first connector will have 4-6 positions to connect up to various sampling points on the chassis ground.
The second connector will have 2 positions that serves as output and goes right to the GND measuring point on the TSMP banana plug.

The reason for this, is that I'd like to fully separate out our TS from GLV components on separate boards whenever possible, particularly if the additional board is only $2. We can work with isolation problems as long as the two systems are separated out on different boards, but if the isolation is occured on a fixed PCB, there's little that can be done to mitigate isolation issues apart from complete board refactoring.

**Review by rgoedken — CHANGES_REQUESTED** [review]
Overall the layout looks nice.
**Major Things:**
- Connectors need to be determined
- There is a connection that is not made in the HV+ path
TSMPC_revision

**Minor Things:**
- The resistors are not uniformly spaced
- The HV+ and HV- traces are spaced 12.7mm apart which is the spacing that is required between HV and GLV traces in PCBs, which we will want between our HV- and HV+ traces (Well done!).  We might want to increase this distance slightly for added factor of safety.

**Review by michaelpass — APPROVED** [review]

**Comment by michaelpass** [comment]
@rgoedken I've added in the necessary changes. You requested.
The only design decision I see is to use 1 or 2 connectors on the output, in a similar fashion to input.

Screen Shot 2019-04-08 at 9 18 08 AM

What do you think?

**Comment by michaelpass** [comment]
Screen Shot 2019-04-10 at 3 41 54 PM

Added in GLV board for TSMP. Pretty self explanatory. X1 gives up to 6 connections to chassis.
The board shorts everything together, and then connectors to X2, which goes to TSMP GND jack.

**Comment by michaelpass** [comment]
Mounting holes fixed.

Screen Shot 2019-04-10 at 3 44 07 PM

**Comment by michaelpass** [comment]
Note: On GLV check out the drill holes for compatibility with connector.

**Review by rgoedken — APPROVED** [review]

**Comment by rgoedken** [comment]
👊

**Pull request merged**
