### PR TITLE
FUSE - Rev A

### PR DESCRIPTION
**Pull request by michaelpass**
Screen Shot 2019-04-08 at 2 50 49 PM

This board is rather simple. It's 24 inputs that go to 24 fuses and 24 outputs. 
My idea is to build 4 of these in total.

@rgoedken You'll want to make sure that all connections are accounted for, and that the dimensions I have posted here line up with the accumulator container.

Here's the docset for the 24P header:
https://drive.google.com/open?id=18psGbjntxlTkZNZCsUFp23M6476aM6iv

### CODE REVIEW

**Comment by michaelpass** [comment]
Here's the measurements on the header: 

Screen Shot 2019-04-08 at 2 56 19 PM

**Comment by anshuman2601** [comment]
Annotation 2019-04-08 150133
Is the white part, a hole or just spacing for the actual connector?
Overall design is compressed well to fit within dimensions.
One concern: If someone has to read the text on the board, there might be issues because of the top wiring. I think it also depends on the board colour.

**Review by anshuman2601 — APPROVED** [review]

**Comment by michaelpass** [comment]
> Is the white part, a hole or just spacing for the actual connector?

It's just an indicator to show where the 1 position starts on the connector. I also added a 1.

> One concern: If someone has to read the text on the board, there might be issues because of the top wiring. I think it also depends on the board colour.

The wiring won't affect this.
Here's a rendering:

Screen Shot 2019-04-08 at 3 07 38 PM

The only thing is the line in the middle of the fuse is messing with the numbers.
But I think it's obvious by count. Plus, all of the fuses are identical.

**Review by rgoedken — CHANGES_REQUESTED** [review]
The layout is very nice and compact.  The connectors look like they should work, but I will need to take measurements of the accumulator to be sure they will work.

**Major Things:**
- We will need to use Nylon machine screws to fasten this board to the accumulator wall because one fuse is very close to the hole for the screw.  We will try to go with #4 screws which have a head diameter of approximately 5.2 mm.  If this was a metal screw, the HV fuse would only be about 1mm away from a screw that would effectively be connected to chassis ground.  We will want to use these Nylon screws for all our HV boards just to ensure no HV line is near a metal screw.  This is all dependent upon if we can get Nylon screws in time.  I have found some and will put them in the parts list so they are ordered right away.
FUSE_revision

-There is a trace and a via that are pretty close to a solder pad.  This could maybe lead to issues if the fuse is not soldered properly.  An unintentional connection could be made.
FUSE_revision_1

**Minor Things:**
-The inputs and outputs on F19 and F20 could be flipped.  It would save some trace length and get rid of two vias.

**Comment by michaelpass** [comment]
> We will need to use Nylon machine screws to fasten this board to the accumulator wall because one fuse is very close to the hole for the screw.  We will try to go with #4 screws which have a head diameter of approximately 5.2 mm.  If this was a metal screw, the HV fuse would only be about 1mm away from a screw that would effectively be connected to chassis ground.  We will want to use these Nylon screws for all our HV boards just to ensure no HV line is near a metal screw.  This is all dependent upon if we can get Nylon screws in time.  I have found some and will put them in the parts list so they are ordered right away.

Noted.

> There is a trace and a via that are pretty close to a solder pad. This could maybe lead to issues if the fuse is not soldered properly. An unintentional connection could be made.

The vias are tented vias. To see this, you can look at the tstop layer.

Screen Shot 2019-04-10 at 4 49 22 AM

The stop layers state where soldermask will *not* be applied. So, it's absent from these vias, meaning that they'll be covered. It will be rather difficult to hand solder onto these. The spacing matters, but it's not further away that many other signal lines. 

I did fixed the overall placement, though:

Screen Shot 2019-04-10 at 5 40 16 AM

> The inputs and outputs on F19 and F20 could be flipped. It would save some trace length and get rid of two vias.

I don't want to place the pre-fused and post-fused parts next to each other. This is why I flipped fuses by row. Signals do likely run close enough to each other that this is a moot point, but I still think it's good practice.

Also, worth considering is that fuses are symmetric parts. Flipping isn't want does the actual electrical connectivity changes. It's the wiring. So in terms of revision, it's the wiring that changes, rather than the part.

**Review by rgoedken — APPROVED** [review]

**Comment by rgoedken** [comment]
👊

**Pull request merged**
