### PR TITLE
CHARGE - Rev A; Initial review requested.

### PR DESCRIPTION
**Pull request by michaelpass**
I've gone with the decision to mount the ZEVA smart precharger on the PCB itself. I removed any heatsinking. All parts have been added to Iowa Formula library. After this pull request and successful merge, all part edits should be in master. 

I'll redo the folder structure for these library files after pulling.

Please review (CADLAB.io, or preferrably EAGLE) changes. Try and identify any missing connections, or notes that are needed on schematic. General tidiness/improvements can be discussed here.

### CODE REVIEW

**Comment by michaelpass** [comment]
Note: Use emoji response to upvote/downvote the initial pull request message.
👍 - Approve
👎 - Disapprove
👊 - Ready to merge (the author of the pull request handles the final merge)

**Comment by anshuman2601** [comment]
The board design is somewhat offset unless the centre is where the ZEVA Pre-charge board is going to be installed.

**Comment by michaelpass** [comment]
> The board design is somewhat offset unless the centre is where the ZEVA Pre-charge board is going to be installed.

I agree. (I'm using a quote here, which I want to do if I'm directly replying to a previous message. I can have multiple quotes here to reply to multiple people in one message. This helps smooth the flow of comments.)

However, the board is as big as it can be. 100mmx100mm is the JLCPC limit for $2.00 boards. We'll also want to not do ENIG to save on money. (Only our more sensitive boards (SC/BSPD, etc.) with lots of tiny connections will need ENIG, by the way.)

I put the components at the top to give better clearance for the ZEVA (there are pins that come out of the sides). [See manual](https://drive.google.com/open?id=17zb8ScRx-2aVZuWGDhtU5de72gOOa4y-).

If we put the components up at the top, it's less wiring that we have to run, and less room for the signals to degrade. We do get more crosstalk though (voltage spikes on one trace affects another).


Note: The wider traces are for traces that carry more power. Most are 24-32 mil.

**Comment by anshuman2601** [comment]
👍 all systems go, "one small step for man, one giant leap for mankind."

**Review by rgoedken — CHANGES_REQUESTED** [review]
Overall it looks good.  The functionality seems like it should work.  A few minor things/questions: ZEVA recommends a 5A fuse on the key supply to the pre-charger, the silkscreen outline of the ZEVA is off because the length of the pre-charger is approximately 76mm (this isn't a problem because there is still plenty of room on the board for it to fit), there are two 10k pull down resistors connected to the input of the AND gate (could possibly remove one), I just want to double check that the red dotted line is the ground plane.  The traces look good and it looks like there is room for a third MOSFET.  Bypass capacitors still need to be placed to ensure the power supply rails are clean for the logic gates.

**Comment by michaelpass** [comment]
> ZEVA recommends a 5A fuse on the key supply to the pre-charger

Added in a 5A fuse. The .lbr file has been added in this branch and will be merged into master for general use after this pull request is completed.
Here's the datasheet:


---


> the silkscreen outline of the ZEVA is off because the length of the pre-charger is approximately 76mm (this isn't a problem because there is still plenty of room on the board for it to fit)

Yep, and the only thing that matters is the clearance, and the hole placement should be spot on.
Here is ZEVA's response to the hole question:

Screen Shot 2019-04-08 at 9 30 50 AM


---


> there are two 10k pull down resistors connected to the input of the AND gate (could possibly remove one)

Yep. This happened because I was "pull-downing" two parts. Forgot to take advantage of the common node. This has been taken care of.

Screen Shot 2019-04-08 at 9 26 30 AM
(This is why)

---

> I just want to double check that the red dotted line is the ground plane. 

Yep. You can also check this by right-clicking the dashed-line and selecting "properties"
(Or using the `info` command in EAGLE and selecting it. There's a lot of great information in here, including the isolation width for the ground pour. 

The actual net connections are controlled by changing the Signal name. You do this for everything in EAGLE (for example, if you add a ground via, but it's not connecting, check the name):

Screen Shot 2019-04-08 at 9 27 47 AM


---


> The traces look good and it looks like there is room for a third MOSFET. 

Added this in. Again, this will be for the discharge resistor. So the discharge_coil+ and discharge_coil- have to be added in to the input connector. Check the revision.

---

> Bypass capacitors still need to be placed to ensure the power supply rails are clean for the logic gates.

Definitely. Added in two ceramic 0805's. "The Art of Electronics 3e (Horowitz, Hill)" recommends 0.1μF to 10μF.
Screen Shot 2019-04-08 at 9 37 52 AM

Screen Shot 2019-04-08 at 9 35 54 AM

Toybuilder on StackExchange also recommended 0.1μF and 1.0μF.
So we'll go with these two.

**Comment by michaelpass** [comment]
Here's the final revisions:

Screen Shot 2019-04-08 at 11 01 29 AM

**Review by rgoedken — APPROVED** [review]

**Comment by rgoedken** [comment]
👊

**Pull request merged**
